services:
  autodok:
    image: autodok
    container_name: autodok
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 30s
      retries: 5
      timeout: 10s
      start_interval: 2s
