version: '3'

services:
  autodok:
    build: .
    container_name: autodok
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
