services:
  autodok:
    image: cars10/autodok
    container_name: autodok
    restart: always
    #ports:
    #  - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      #- /home/user/.docker/config.json:/config.json
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 30s
      retries: 5
      timeout: 10s
      start_interval: 2s
